### ISSUE TITLE
ValueTable parsing for messages with extended id

### ISSUE THREAD

**Issue by hakwes** [EFeru/DbcParser#10]
It seems that ValueTables can not be parsed for messages with extended id's.

Example:
`BO_ 2566896411 ACSmessage1_L: 8 ArticulationControl_L
 SG_ CurrentLeft : 16|16@1+ (1,0) [0|4092] ""  ArticulationControl_L
 SG_ FeedbackLeft : 0|16@1+ (1,0) [0|4092] ""  ArticulationControl_L
 SG_ PropValveLeftError : 48|1@1+ (1,0) [0|1] "" Vector__XXX
 SG_ IgnitionRelayNode2Error : 49|1@1+ (1,0) [0|1] "" Vector__XXX
 SG_ Master_Slave : 56|2@1+ (1,0) [0|3] "" Vector__XXX
 SG_ PropValveLeftShortCircuit : 50|1@1+ (1,0) [0|0] "" Vector__XXX

VAL_ 2566896411 PropValveLeftError 0 "False" 1 "True" 2 "Error" ;
VAL_ 2566896411 IgnitionRelayNode2Error 0 "False" 1 "True" ;
VAL_ 2566896411 Master_Slave 0 "Node2Slave" 1 "NotDefined" 2 "Node2Master" 3 "NotDefined" ;
VAL_ 2566896411 PropValveLeftShortCircuit 0 "False" 1 "True" ;`

I think the check for extendeded id is missing in the [LinkTableValuesToSignal](https://github.com/EFeru/DbcParser/blob/0b4963db1b841c7d74b69754990a2fc04570a53e/DbcParserLib/DbcBuilder.cs#L69)

**Comment by EFeru** [comment]
Fixed in #11
