### ISSUE TITLE
Signal.Length >255 

### ISSUE THREAD

**Issue by taylorjdlee** [EFeru/DbcParser#18]
#17 Is still not fixed both line 64 and 97 in SignalLineParser.cs need to be changed to ushort.Parse instead of byte.Parse

https://github.com/EFeru/DbcParser/blob/aa1a163ddda16367dfc6b3ca0f698a2bd2fb4c6a/DbcParserLib/Parsers/SignalLineParser.cs#L64

https://github.com/EFeru/DbcParser/blob/aa1a163ddda16367dfc6b3ca0f698a2bd2fb4c6a/DbcParserLib/Parsers/SignalLineParser.cs#L97

**Comment by taylorjdlee** [comment]
Hi @EFeru wonder if you could approve this PR as I'm currently waiting on it thanks!

**Comment by EFeru** [comment]
Hi @taylorjdlee . Sorry i missed your PR, i just saw it now. It is merged. Thank you very much for you contribution!
