### ISSUE TITLE
Add support for Environment variables when parsing dbc files

### ISSUE THREAD

**Issue by mtooooo** [EFeru/DbcParser#21]
As the title

**Comment by EFeru** [comment]
Hi @mtooooo, Sorry, I don't fully understand. Can you be more specific on the needs you have?

**Comment by Adhara3** [comment]
@EFeru dbc can specify environment variables using tag `EV_`
We can have a look at this. Lower priority, but can be done.

A

**Comment by mtooooo** [comment]
Vector CANdb++ Editor show.
[Snipaste_2023-01-28_17-16-21.jpg](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/377f97d98b2842d3870bca5f57da7773~tplv-k3u1fbpfcp-watermark.image?)

**Comment by Whitehouse112** [comment]
@mtooooo can you provide the entire .dbc file shown in the image?

I tried to copy your `EV_` lines into my test file but i get a .dbc file that can't be opened with Vector CANdb++ (version 3.1.21) Which version of CANdb++ are you using?

**Comment by mtooooo** [comment]
Dear all,

&nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp; &nbsp; I'm use&nbsp; CANdb++ Version 3.1.21.&nbsp; &nbsp; &nbsp;EH6466.dbc&nbsp;file is attached to the mailbox。

Thanks!







&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Feb 16, 2023 02:30 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [EFeru/DbcParser] Add support for Environment variables when parsing dbc files (Issue #21)

&nbsp;



 
@mtooooo can you provide the entire .dbc file shown in the image?
 
I tried to copy your EV_ lines into my test file but i get a .dbc file that can't be opened with Vector CANdb++ (version 3.1.21) Which version of CANdb++ are you using?

**Comment by Adhara3** [comment]
Please @mtooooo , do drag and drop the dbc file here, in your reply message. 
The file should get attached to your message.

Thanks

**Comment by mtooooo** [comment]
Re: [EFeru/DbcParser] Add support for Environment variables when parsing dbc files (Issue #21)
-----------------------------------

 

 
Please @mtooooo , do drag and drop the dbc file here, in your reply message.
 The file should get attached to your message.
 
Thanks

**Comment by mtooooo** [comment]
[EH6466.zip](https://github.com/EFeru/DbcParser/files/10762715/EH6466.zip)

**Comment by mtooooo** [comment]
using Vector CANdb++ (version 3.1.21).
