### ISSUE TITLE
Question on INextLineProvider

### ISSUE THREAD

**Issue by lnetx** [EFeru/DbcParser#36]
I have a question， The INextLineProvider type  is not used in ILineParser type ，so why TryParse function has a type of INextLineProvider  parameter ,  is  for what ?

**Comment by Whitehouse112** [comment]
Hi,
a comment in a DBC file can have multiple lines, so the `CommentLineParser` needs to be able to read multiple lines (if any) and uses the `INextLineProvider` in its own `TryParse`'s implementation
