### ISSUE TITLE
Problem to parse DBC files using DbcParser in ASP.NET project

### ISSUE THREAD

**Issue by benazirsultana** [EFeru/DbcParser#56]
Hello,
I wanted to parse dbc messages from a .dbc file in ASP.NET project using your dbc parser. I have a line in my dbc file like bellow:
BA_ "GenSigStartValue" SG_ 2364604659 PDU_Act_VehicleSoH 637.5;

![image](https://github.com/EFeru/DbcParser/assets/99539535/fff3bce9-3907-4293-94aa-50e5fb633395)

According to: reference on http://mcu.so/Microcontroller/Automotive/dbc-file-format-documentation_compress.pdf
Meaning of that line: 
'BA_' attribute_name 'SG_' message_id signal_name attribute_value ';' ;

According to documentation, attribute_value could be float.
attribute_value = unsigned_integer | signed_integer | double | char_string; (http://mcu.so/Microcontroller/Automotive/dbc-file-format-documentation_compress.pdf)

but I was unable to get the value of GenSigStartValue as 637.5. 
Using release 1.3.3, I got an exception ("Input string was not in a correct format").
Using latest release 1.4.2, I got the value of GenSigStartValue as 0(which is not desirable). 
![image](https://github.com/EFeru/DbcParser/assets/99539535/2015ceda-2ebf-4cf1-b935-c22d3946ea59)

Could you please suggest me how to overcome this problem?
Advance thank you.

**Comment by Whitehouse112** [comment]
Hi @benazirsultana,
have you check the definition of the `GenSigStartValue` property? From the image I see that is defined as `Integer property` and `637.5` is not a valid number (we recently added [parsing failures management](https://github.com/EFeru/DbcParser#parsing-errors-management) to retrieve errors like this one).

Regards

**Comment by Adhara3** [comment]
Without any feedback, I do close this issue
