### ISSUE TITLE
An exception is thrown when the value contains a space after the quotes

### ISSUE THREAD

**Issue by JendaBe** [EFeru/DbcParser#57]
When parsing the following line in a DBC file
VAL_ 1234 Signal_Name 0 "24h" 1 " 12h AM/PM" ;
an exception is thrown from the ExtensionsAndHelpers.ToDictionary.
The code
var valueTable = match.Groups[4].Value.TrimStart().Replace("\" ", "\"" + Environment.NewLine);
in ValueTableLineParser.TryParse replaces space between 12h by the new line and it causes an exception.

**Comment by Whitehouse112** [comment]
Hi @JendaBe ,
thanks for spot the issue. The fix is ready and will be available in the next release.

Regards
