### ISSUE TITLE
Update Target Frameworks

### ISSUE THREAD

**Issue by Uight** [EFeru/DbcParser#69]
Currently in the target frameworks of the project the following are listed:
netstandard2.0;net461;net5.0;net6.0

i would consider changing it a bit for the following reasons:
net461 is out of support since beginning of 2022 therefor atleast use net462 which is still officialy supported.
net5.0 is out of support;
net6.0 runs out of support this year but is okay for now;
netstandard2.0 is kind of tricky but as its currently supported you would probably keep supporting it.

net framework support:
https://learn.microsoft.com/de-de/lifecycle/products/microsoft-net-framework
.net support:
https://dotnet.microsoft.com/en-us/platform/support/policy
.net standard infos:
https://learn.microsoft.com/en-us/dotnet/standard
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-5-and-net-standard

I would like to change supported frameworks to:
netstandard2.0;net462;net6.0;net8.0

**Comment by Adhara3** [comment]
Sound reasoable

**Comment by Uight** [comment]
was solved with the merge of the pull request
