### ISSUE TITLE
Empty node list is currently not supported

### ISSUE THREAD

**Issue by Adhara3** [EFeru/DbcParser#81]
The tag `BU_:` with no nodes produces a parsing error.
We should tolerate this.

**Comment by Uight** [comment]
true and easy enough. and as it is internally a hashset thats always initialized it wouldn't cause the public IEnumerable<Node> Nodes {get;} to ever be null which i like ;)

**Comment by Adhara3** [comment]
@Whitehouse112

**Comment by Adhara3** [comment]
@Whitehouse112 can you please take care of this one?

Thx
A

**Comment by Whitehouse112** [comment]
Of course, no problem
