### ISSUE TITLE
Unable to release package

### ISSUE THREAD

**Issue by Adhara3** [EFeru/DbcParser#84]
@EFeru I can't release for some reason

> Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)

Any idea?

Thanks
A

**Comment by EFeru** [comment]
Could be that I have to login once on nuget to confirm allowance for the next 1 year.

**Comment by EFeru** [comment]
I will check in 30min

**Comment by EFeru** [comment]
@Adhara3 Can you try now? the API KEY expired and I renewed it now.

**Comment by Adhara3** [comment]
@EFeru , it worked, thanks a lot! 1.7.0 released to nuget

**Comment by EFeru** [comment]
Excellent. Many thanks for your efforts on this release! I apologize for not being active to support you.
